### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by ericvanderlinden** [acdh-oeaw/djangobase-cookiecutter#1]
cookiecutter gh:acdh-oeaw/djangobase-cookiecutter
=>
Unable to create file '.github/workflows/test.yml'
Error message: 'env' is undefined
Context: {
    "cookiecutter": {
        "_copy_without_render": [
            "*.html"
        ],
        "_template": "gh:acdh-oeaw/djangobase-cookiecutter",
        "directory_name": "ssg/public/jedar",
        "project_abbr": "jedar",
        "project_title": "JSONLD Editor"
    }
}

**Comment by csae8092** [comment]
Looking into it. Thanks for reporting!
